// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// subsetAndUpdate
List subsetAndUpdate(DateVector From, DateVector To, int maxDiff);
RcppExport SEXP _neatRanges_subsetAndUpdate(SEXP FromSEXP, SEXP ToSEXP, SEXP maxDiffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type From(FromSEXP);
    Rcpp::traits::input_parameter< DateVector >::type To(ToSEXP);
    Rcpp::traits::input_parameter< int >::type maxDiff(maxDiffSEXP);
    rcpp_result_gen = Rcpp::wrap(subsetAndUpdate(From, To, maxDiff));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neatRanges_subsetAndUpdate", (DL_FUNC) &_neatRanges_subsetAndUpdate, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_neatRanges(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
