# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateAndSubset <- function(From, To, max_gap) {
    .Call(`_neatRanges_updateAndSubset`, From, To, max_gap)
}

updateAndSubsetTime <- function(From, To, max_gap) {
    .Call(`_neatRanges_updateAndSubsetTime`, From, To, max_gap)
}

