globalVariables(c("gap_between",
                  "lead_max",
                  "max_until_now",
                  "Expanded",
                  "rn",
                  ".",
                  "rl",
                  "seqsEnd",
                  "seqs")
                )
